package greeting

import com.example.User
import com.example.GreetingMessage

rule "Early morning rule" no-loop true
when
    user : User()
    eval(user.now() < 6 )
then
    GreetingMessage msg = new GreetingMessage();
    msg.setMessage("Good Early Morning  " + user.getName() + " !!! ");
    insertLogical(msg);
end

rule "Is Morning" no-loop true
when
    user : User()
    eval((6 <= user.now()) && (user.now()< 12))
then
    GreetingMessage msg = new GreetingMessage();
    msg.setMessage("Good Morning  " + user.getName() + " !!! ");
    insertLogical(msg);
end

rule "Is afternoon" no-loop true
when
    user : User()
    eval((12 <= user.now()) && (user.now() < 18))
then
    GreetingMessage msg = new GreetingMessage();
    msg.setMessage("Good Afternoon  " + user.getName() + " !!! ");
    insertLogical(msg);
end

rule "Is Night" no-loop true
when
    user : User()
    eval( (18 <= user.now()) && (user.now() < 24))
then
    GreetingMessage msg = new GreetingMessage();
    msg.setMessage("Good Night  " + user.getName() + " !!! ");
    insertLogical(msg);
end
	